qlib_init:
    provider_uri: "/home/bartender/src/qlib_bin"
    region: cn
market: &market all
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2025-06-30
    fit_start_time: 2008-01-01
    fit_end_time: 2023-10-31
    instruments: *market
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 5
            n_drop: 5
    backtest:
        start_time: 2024-01-01
        end_time: 2025-06-30
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: ["$close>=($high_limit)", "$close<=($low_limit)"]
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            colsample_bytree: 0.8879
            learning_rate: 0.2
            subsample: 0.8789
            lambda_l1: 205.6999
            lambda_l2: 580.9768
            max_depth: 8
            num_leaves: 210
            num_threads: 20
            seed: 42
            feature_fraction: 0.9
            bagging_fraction: 0.8
            bagging_freq: 5
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: JQ260
                module_path: factor_loader.JQ260_vwap_wo_qfeature_5d
                kwargs: *data_handler_config
            segments:
                train: [2008-01-01, 2023-10-31]
                valid: [2023-11-01, 2023-12-31]
                test: [2024-01-01, 2025-06-30]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
