qlib_init:
    provider_uri: "/home/bartender/src/qlib_bin"
    region: cn
experiment: jq260_test_3d
market: &market all
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2008-01-01
    end_time: 2025-07-18
    fit_start_time: 2010-01-01
    fit_end_time: 2023-12-31
    instruments: *market
port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal: <PRED>
            topk: 50
            n_drop: 5
    backtest:
        start_time: 2024-01-01
        end_time: 2025-07-17
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: ["Or($close>=($high_limit),$is_index > 0)", "Or($close<=($low_limit),$is_index > 0)"]
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
task:
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: binary
            metric: [ 'auc', 'binary_logloss']
            colsample_bytree: 0.8879
            learning_rate: 0.2
            subsample: 0.8789
            lambda_l1: 205.6999
            lambda_l2: 580.9768
            max_depth: 8
            num_leaves: 50
            num_threads: 20
            seed: 42
            feature_fraction: 0.9
            bagging_fraction: 0.8
            bagging_freq: 5
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: JQ260
                module_path: factor_loader.JQ260_TEST_5d
                kwargs: *data_handler_config
            segments:
                train: [2010-01-01, 2023-12-31]
                valid: [2024-10-01, 2024-12-31]
                test: [2024-01-01, 2025-07-10]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
